version: '3.9'

services:
  backend:
    build:
      context: ../../apps/hello-world-backend
      dockerfile: Dockerfile.dev
    env_file:
      - ../../apps/hello-world-backend/.env
    container_name: backend
    ports:
      - "8000:8000"

  teacher-web:
    build:
      context: ../../apps/hello-world-nextjs
      dockerfile: Dockerfile.dev
    env_file:
      - ../../apps/hello-world-nextjs/.env
    container_name: teacher-web
    ports:
      - "3000:3000"

  postgresql_db:
    image: postgres:15
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hello-world-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: