version: '3.9'

services:
  backend:
    build:
      context: ../../apps/hello-world-backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgresql_db

  teacher-web:
    build:
      context: ../../apps/hello-world-nextjs
      dockerfile: Dockerfile.dev
    container_name: teacher-web
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql_db:
    image: postgres:15
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=value
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hello-world-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: